# Generated by Django 4.2 on 2023-07-12 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookiestand',
            old_name='ocation',
            new_name='location',
        ),
    ]
